### ISSUE TITLE
Backup files being created every one or two seconds - filling up SD car

### ISSUE THREAD

**Issue by ghormann** [bbarke/brp-fpp-voting#13]
Copied from: https://github.com/FalconChristmas/fpp/issues/1694  as issue only happens when plugin installed. 

Version Info:

FPP Version: | 7.3.5
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v2023-11
OS Version: | Raspbian GNU/Linux 11 (bullseye)
Hardware Serial Number: | 1000000026a501ce
Kernel Version: | 6.1.21-v7l+
System Boot Time: | 2023-12-03 16:19:23
fppd Uptime: | 53:47
Local Git Version: | https://github.com/FalconChristmas/fpp/commit/a4434abb2a2ff92f9ba23e023f47c64bc615e8a1 ChangeLog
Remote Git Version: | https://github.com/FalconChristmas/fpp/commit/a4434abb2a2ff92f9ba23e023f47c64bc615e8a1

Issue
~/media/config/backups is filling up with backup files being created every second or so as shown below.

-rw-r--r-- 1 fpp fpp 575772 Dec 3 17:07 MasterFPP_all-backup_v7_20231203170749.json
-rw-r--r-- 1 fpp fpp 575772 Dec 3 17:07 MasterFPP_all-backup_v7_20231203170751.json
-rw-r--r-- 1 fpp fpp 575772 Dec 3 17:07 MasterFPP_all-backup_v7_20231203170753.json
-rw-r--r-- 1 fpp fpp 575772 Dec 3 17:07 MasterFPP_all-backup_v7_20231203170754.json

Over the last couple of days, 25,710+ files were created, consuming 14,492,360 bytes. I'm able to delete them, but I have to keep an eye on this before the 32G SD card fills up.

This is a bare install using 7.0, which I then upgraded to the latest version. I only run 3 add-ins on this machine: Big Buttons, BRP Voting, and Falcon Hardware Monitor. It is running as Master. While I am seeing backup files being created in another 7.3.5 install that I am running as a backup (in Remote mode), these are less frequent, and based on what I'm seeing on other devices, normal, as shown below.

-rw-r--r-- 1 fpp fpp 535303 Dec 2 12:21 YardMaster_all-backup_v7_20231202122109.json
-rw-r--r-- 1 fpp fpp 535334 Dec 2 16:43 YardMaster_all-backup_v7_20231202164319.json
-rw-r--r-- 1 fpp fpp 535334 Dec 2 23:26 YardMaster_all-backup_v7_20231202232614.json
-rw-r--r-- 1 fpp fpp 535334 Dec 3 13:26 YardMaster_all-backup_v7_20231203132625.json
-rw-r--r-- 1 fpp fpp 535334 Dec 3 13:33 YardMaster_all-backup_v7_20231203133356.json

Log files attached.When the plugin is installed,

**Comment by bbarke** [comment]
Thanks for this report - it looks to have been something introduced into 7.0: https://github.com/FalconChristmas/fpp/releases/tag/7.0

https://github.com/bbarke/brp-fpp-voting/blob/master/vote.php#L128
and
https://github.com/bbarke/brp-fpp-voting/blob/master/scripts/vote-service.py#L385-L413

We use the config endpoint pretty heavily to show the status of the songs, and every time we save the configurations. I'll get an update for this soon - probably by bypassing the endpoint inside of the vote-service.py by locating and update the file directly.

**Comment by jaredb7** [comment]
Hi @bbarke, there's a bug on the FPP side in the logic handling how many backups to keep. Even with the constant writing of settings it should be only keeping a fixed number of backups. We'll fix this.

The only other small issue I just realised is that eventually valid FPP settings backups will get pushed out as the plugin writes it's back it's settings and we end up with the last e.g 45 backups being all triggered from the plugin and for example the script or event change the user made a few days before has been deleted. This isn't the plugins fault though, just a side effect of how the auto backups work.

I'm thinking we could try add some logic to just keep the last 5 backups triggered by a plugin.

**Comment by bbarke** [comment]
@jaredb7 thanks for those details, keeping 5 backups for a plugin is a great idea. For the time being though I adjusted the service to write to the plugin settings file directly, so status messages won't trigger the backup. Saving a configuration from the plugin page will still go though the endpoint though so that'll still create a backup but it won't create one every second anymore.
